let oneCoord = [[{
  image: "/img/team/prathyusha.jpg",
  designation: "Hospitality",
	fbURL: "https://www.facebook.com/profile.php?id=100006150706884",
	twURL: "https://www.facebook.com/profile.php?id=100006150706884",
  name: "T Pratyusha",
	phone: "+918464097474",
  email: "ee14btech11034@iith.ac.in",
}, {
  image: "/img/team/anshuman.jpg",
  designation: "Hospitality",
	fbURL: "https://www.facebook.com/anshuman.pasupalak1",
	twURL: "https://www.facebook.com/anshuman.pasupalak1",
  name: "P Anshuman",
	phone: "+919705469468",
  email: "ch14btech11020@iith.ac.in",
}, {
  image: "/img/team/sunil.jpg",
  designation: "Transport",
	fbURL: "https://www.facebook.com/sunil.krishnakumar.921",
	twURL: "https://www.facebook.com/sunil.krishnakumar.921",
  name: "Sunil K",
	phone: "+918686096380",
  email: "me14btech11023@iith.ac.in",
}], [{
  image: "/img/team/jyonit.jpg",
  designation: "Security",
	fbURL: "https://www.facebook.com/jyonit.gupta",
	twURL: "https://www.facebook.com/jyonit.gupta",
  name: "Jyonit Gupta",
	phone: "+919638659949",
  email: "me14btech11018@iith.ac.in",
}, {
  image: "/img/team/anudeep.jpg",
  designation: "Infrastructure",
	fbURL: "https://www.facebook.com/deepu.chkvs",
	twURL: "https://www.facebook.com/deepu.chkvs",
  name: "Ch Anudeep",
	phone: "+919490928575",
  email: "cs13b1009@iith.ac.in",
}]];

let twoCoord = [[{
  image: "/img/team/nirupama.jpg",
  designation: "Creatives",
	fbURL: "https://www.facebook.com/nirupama.parseneti",
	twURL: "https://www.facebook.com/nirupama.parseneti",
  name: "Nirupama P",
	phone: "+919014831218",
  email: "ee14btech11025@iith.ac.in",
}, {
  image: "/img/team/vivek.jpg",
  designation: "Creatives",
	fbURL: "https://www.facebook.com/svivek.pillai",
	twURL: "https://www.facebook.com/svivek.pillai",
  name: "Vivek S",
	phone: "+919685804419",
  email: "me14btech11032@iith.ac.in",
}, {
  image: "/img/team/vibhas.jpg",
  designation: "Creatives",
	fbURL: "https://www.facebook.com/vibhas.goyal",
	twURL: "https://www.facebook.com/vibhas.goyal",
  name: "Vibhas Goyal",
	phone: "+919603740090",
  email: "es14btech11021@iith.ac.in",
}], [{
  image: "/img/team/gouthi.jpg",
  designation: "Web",
	fbURL: "https://www.facebook.com/veeramachaneni.goutham",
	twURL: "https://www.facebook.com/veeramachaneni.goutham",
  name: "Goutham V",
	phone: "+919959552408",
  email: "cs14btech11014@iith.ac.in",
}, {
  image: "/img/team/chandan.png",
  designation: "Web",
	fbURL: "https://www.facebook.com/chandan.sinha.142",
	twURL: "https://www.facebook.com/chandan.sinha.142",
  name: "Chandan Sinha",
	phone: "+919494826729",
  email: "me13b1009@iith.ac.in",
}], [{
  image: "/img/team/mahesh.jpg",
  designation: "Campus Publicity",
	fbURL: "https://www.facebook.com/mahesh.jakkapu",
	twURL: "https://www.facebook.com/mahesh.jakkapu",
  name: "Mahesh J",
	phone: "+918333970939",
  email: "ep14btech11004@iith.ac.in",
}, {
  image: "/img/team/shruthi.jpg",
  designation: "Campus Publicity",
	fbURL: "https://www.facebook.com/shruti.badadhe.1",
	twURL: "https://www.facebook.com/shruti.badadhe.1",
  name: "B Shruti Ekanath",
	phone: "+917680810104",
  email: "cs14btech11005@iith.ac.in",
}]];

let threeCoord = [[{
  image: "/img/team/pooja.jpg",
  designation: "Online Publicity",
	fbURL: "https://www.facebook.com/pooja.sri.904",
	twURL: "https://www.facebook.com/pooja.sri.904",
  name: "Pooja",
	phone: "+918331942496",
  email: "ce14btech11024@iith.ac.in",
}, {
  image: "/img/team/vasudha.jpg",
  designation: "Online Publicity",
	fbURL: "https://www.facebook.com/vasudha.kapre",
	twURL: "https://www.facebook.com/vasudha.kapre",
  name: "Vasudha Kapre",
	phone: "+919491948280",
  email: "ce14btech11021@iith.ac.in",
}, {
  image: "/img/team/nagendra.jpg",
  designation: "Online Publicity",
	fbURL: "https://www.facebook.com/nagendra.sainath.7",
	twURL: "https://www.facebook.com/nagendra.sainath.7",
  name: "Nagendra Sainath",
	phone: "+91 8985263834",
  email: "cs13b1023@iith.ac.in",
}], [{
  image: "/img/team/radhika.jpg",
  designation: "Informals",
	fbURL: "https://www.facebook.com/profile.php?id=100007959468315",
	twURL: "https://www.facebook.com/profile.php?id=100007959468315",
  name: "Radhika Deshpande",
	phone: "+918464090464",
  email: "es14btech11006@iith.ac.in",
}, {
  image: "/img/team/jhonny.jpg",
  designation: "Informals",
	fbURL: "https://www.facebook.com/jagdish.charan.19",
	twURL: "https://www.facebook.com/jagdish.charan.19",
  name: "Jagdish Singh Charan",
	phone: "+917658963203",
  email: "cs14btech11017@iith.ac.in",
}], [{
  image: "/img/team/ali.jpg",
  designation: "Events",
	fbURL: "https://www.facebook.com/ali.hyder.507",
	twURL: "https://www.facebook.com/ali.hyder.507",
  name: "Ali Hyder",
	phone: "+918297617063",
  email: "ee13b1041@iith.ac.in",
}, {
  image: "/img/team/rahul.jpg",
  designation: "Workshops & EML",
	fbURL: "https://www.facebook.com/rahulpagidala999",
	twURL: "https://www.facebook.com/rahulpagidala999",
  name: "Rahul Pagidala",
	phone: "+919959355294",
  email: "ee14btech11023@iith.ac.in",
}]]


let fourCoord = [[{
  image: "/img/team/soumitra.jpg",
  designation: "Marketing",
	fbURL: "https://www.facebook.com/soumitra.khanale",
	twURL: "https://twitter.com/SoumitraKhanale",
  name: "Soumitra Khanale",
	phone: "+91 9949174386",
  email: "me14btech11022@iith.ac.in",
}, {
  image: "/img/team/niranjan.jpg",
  designation: "Marketing",
	fbURL: "https://www.facebook.com/sai.n.reddy1",
	twURL: "https://www.facebook.com/sai.n.reddy1",
  name: "Niranjan",
	phone: "+919014611990",
  email: "es14btech11011@iith.ac.in",
}, {
  image: "/img/team/dinesh.jpg",
  designation: "Marketing",
	fbURL: "https://www.facebook.com/dinesh.venkatarathna",
	twURL: "https://www.facebook.com/dinesh.venkatarathna",
  name: "B V Dinesh",
	phone: "+919948698956",
  email: "ch14btech11004@iith.ac.in",
}], [{
  image: "/img/team/mudit.jpg",
  designation: "Marketing",
	fbURL: "https://www.facebook.com/mudit.gupta.05",
	twURL: "https://www.facebook.com/mudit.gupta.05",
  name: "Mudit Gupta",
	phone: "+91 9705731498",
  email: "es14btech11012@iith.ac.in",
}, {
  image: "/img/team/ganesh.jpg",
  designation: "Finance",
	fbURL: "https://www.facebook.com/rocking.ganesh.50",
	twURL: "https://www.facebook.com/rocking.ganesh.50",
  name: "Sai Ganesh",
	phone: "+917306797067",
  email: "ce14btech11016@iith.ac.in",
}]];

let team = [{
	manager: "Manager 1",
	managerFor: "Security, Infra, Hospi",
	image: "/img/team/ashruth.jpg",
	fbURL: "https://www.facebook.com/ashruthvallabdhas",
  twURL: "https://www.facebook.com/ashruthvallabdhas",
  name: "Ashruth V",
  phone: "+919052678066",
  email: "es13b1023@iith.ac.in",
  coordinators: [oneCoord]
}, {
	manager: "Manager 2",
	managerFor: "Web, Creatives and Campus Publicity",
	image: "/img/team/thuglife.jpg",
	fbURL: "https://www.facebook.com/sinu.nayak.1",
  twURL: "https://twitter.com/sinu1007",
  name: "L Srinivas Naik",
  phone: "+917702255616",
  email: "cs13b1021@iith.ac.in",
  coordinators: [twoCoord]
}, {
	manager: "Manager 3",
	managerFor: "Events, Online Publicity and Worskhops",
	image: "/img/team/karnati.jpg",
	fbURL: "https://www.facebook.com/profile.php?id=100009214010576",
  twURL: "https://www.facebook.com/profile.php?id=100009214010576",
  name: "Karthik Karnati",
  phone: "+918297808380",
  email: "ch13b1010@iith.ac.in",
  coordinators: [threeCoord]
}, {
	manager: "Manager 4",
	managerFor: "Marketing, Finance and Exhibition",
	image: "/img/team/ramoji.jpg",
	fbURL: "https://www.facebook.com/cherukuri.ramoji",
  twURL: "https://www.facebook.com/cherukuri.ramoji",
  name: "Ramoji Rao",
  phone: "+918374019777",
  email: "ce13b1005@iith.ac.in",
  coordinators: [fourCoord]
}]

module.exports = team;
